/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlisinhvien;


import DAO.ThongKeDAO;
import Utils.Auth;
import Utils.MsgBox;
import Utils.ximage;
import javax.swing.JOptionPane;

import quanlysv.DoiMatKhau;

/**
 *
 * @author akbro
 */
public class TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    // mo giao dien dang nhap
    public void openDangNhap(){
        DangNhap frame = new DangNhap();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }
    // mo giao dien doi mat khau
    public void openDoiMatKhau() {

        if (Auth.isLogin()) {
            DoiMatKhau frame = new DoiMatKhau();
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);
//                    frame.dispose();
        } else {
            MsgBox.alert(this, "Vui Lòng Đăng Nhập");
        }
    }
// xu ly quyen truy cap
    public void accessRight() {
        if (!Auth.isManager().equalsIgnoreCase("Admin")) {
            mniDoiMatKhau.setVisible(false);
            mniQuanLiNguoiDung.setVisible(false);
            mniKhoa.setVisible(false);
            mniQuanLiGiangVien.setVisible(false);
            btnQLGiangVien.setVisible(false);
            btnQLKhoa.setVisible(false);
            mnuThongKe.setVisible(false);
            mniQuanLiNguoiDung.setVisible(false);
        }
    }
    // mo quan li diem
    public void openQuanLiDiem(){
        QuanLiDiem frame = new QuanLiDiem();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }
    // mo quan li giang vien
    public void openQuanLiGiangVien(){
        QuanLiGiangVien frame = new QuanLiGiangVien();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);

    }
    //mo quan li khoa
    public void openQuanLiKhoa(){
        QuanLiKhoa frame = new QuanLiKhoa();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }
    // mo quan li lop
    public void openQuanLiLop(){
        QuanLiLop frame = new QuanLiLop();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }
    // mo quan li mon hoc
    public void openQuanLiMonHoc(){
        QuanLiMonHoc frame = new QuanLiMonHoc();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }
    // mo quan li nguoi dung
    public void openQuanLiNguoiDung(){
        QuanLiNGuoiDung frame = new QuanLiNGuoiDung();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }
    // mo quan li Sinh Vien
    public void openQuanLiSinhVien(){
        QuanLiSinhVien frame = new QuanLiSinhVien();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }
     // mo tim kiem diem
    public void openTimKiemDiem(){
        TimKiemDiem frame = new TimKiemDiem();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }
    // nut dang xuat
    public void dangXuat(){
        Auth.clear();
        DangNhap Login = new DangNhap();
        this.dispose();
	Login.setVisible(true);
	Login.setLocationRelativeTo(null);
    }
    public TrangChu() {
        initComponents();
        accessRight();
        setIconImage(ximage.getAppIcon());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnQLSinhVien = new javax.swing.JButton();
        btnQLGiangVien = new javax.swing.JButton();
        btnQuanLyDiemSV = new javax.swing.JButton();
        btnQLKhoa = new javax.swing.JButton();
        btnQLLop = new javax.swing.JButton();
        btnQLMonHoc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        mniDangNhap = new javax.swing.JMenuItem();
        mniDoiMatKhau = new javax.swing.JMenuItem();
        mniDangXuat = new javax.swing.JMenuItem();
        mniQuanLiNguoiDung = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniExit = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mniMon = new javax.swing.JMenuItem();
        mniKhoa = new javax.swing.JMenuItem();
        mniLop = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mniQuanLiSinhVien = new javax.swing.JMenuItem();
        mniQuanLiGiangVien = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniQuanLiDiem = new javax.swing.JMenuItem();
        mnuTimKiem = new javax.swing.JMenu();
        mniTimKiemDiem = new javax.swing.JMenuItem();
        mnuThongKe = new javax.swing.JMenu();
        mniTKTongKet = new javax.swing.JMenu();
        mniDSSinhVien = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hệ Thống Quản Lý Trường Đại Học");

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        btnQLSinhVien.setText("QL SINH VIÊN");
        btnQLSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSinhVienActionPerformed(evt);
            }
        });

        btnQLGiangVien.setText("QL GIẢNG VIÊN");
        btnQLGiangVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLGiangVienActionPerformed(evt);
            }
        });

        btnQuanLyDiemSV.setText("QL ĐIỂM SV");
        btnQuanLyDiemSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyDiemSVActionPerformed(evt);
            }
        });

        btnQLKhoa.setText("QL KHOA");
        btnQLKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLKhoaActionPerformed(evt);
            }
        });

        btnQLLop.setText("QL LỚP");
        btnQLLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLLopActionPerformed(evt);
            }
        });

        btnQLMonHoc.setText("QL MÔN HỌC");
        btnQLMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLMonHocActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/DT.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQLSinhVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQLGiangVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuanLyDiemSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQLKhoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQLLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQLMonHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnQLSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnQLGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnQuanLyDiemSV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnQLKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnQLLop, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnQLMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(64, 64, 64))
        );

        jMenu2.setText("Hệ thống");

        mniDangNhap.setText("Đăng nhập");
        mniDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangNhapActionPerformed(evt);
            }
        });
        jMenu2.add(mniDangNhap);

        mniDoiMatKhau.setText("Đổi mật khẩu");
        mniDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoiMatKhauActionPerformed(evt);
            }
        });
        jMenu2.add(mniDoiMatKhau);

        mniDangXuat.setText("Đăng xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        jMenu2.add(mniDangXuat);

        mniQuanLiNguoiDung.setText("Quản lí người dùng");
        mniQuanLiNguoiDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQuanLiNguoiDungActionPerformed(evt);
            }
        });
        jMenu2.add(mniQuanLiNguoiDung);
        jMenu2.add(jSeparator1);

        mniExit.setText("Exit");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        jMenu2.add(mniExit);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Danh mục");

        mniMon.setText("Môn");
        mniMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniMonActionPerformed(evt);
            }
        });
        jMenu3.add(mniMon);

        mniKhoa.setText("Khoa");
        mniKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKhoaActionPerformed(evt);
            }
        });
        jMenu3.add(mniKhoa);

        mniLop.setText("Lớp");
        mniLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLopActionPerformed(evt);
            }
        });
        jMenu3.add(mniLop);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Quản lí");

        mniQuanLiSinhVien.setText("Quản lí sinh viên");
        mniQuanLiSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQuanLiSinhVienActionPerformed(evt);
            }
        });
        jMenu4.add(mniQuanLiSinhVien);

        mniQuanLiGiangVien.setText("Quản lí giảng viên");
        mniQuanLiGiangVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQuanLiGiangVienActionPerformed(evt);
            }
        });
        jMenu4.add(mniQuanLiGiangVien);
        jMenu4.add(jSeparator2);

        mniQuanLiDiem.setText("Quản lí điểm");
        mniQuanLiDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQuanLiDiemActionPerformed(evt);
            }
        });
        jMenu4.add(mniQuanLiDiem);

        jMenuBar1.add(jMenu4);

        mnuTimKiem.setText("Tìm kiếm");

        mniTimKiemDiem.setText("Tìm Kiếm Điểm");
        mniTimKiemDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTimKiemDiemActionPerformed(evt);
            }
        });
        mnuTimKiem.add(mniTimKiemDiem);

        jMenuBar1.add(mnuTimKiem);

        mnuThongKe.setText("Thống kê");

        mniTKTongKet.setText("Điểm tổng kết sinh viên");
        mniTKTongKet.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mniTKTongKetMenuSelected(evt);
            }
        });
        mniTKTongKet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniTKTongKetMouseClicked(evt);
            }
        });
        mniTKTongKet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTKTongKetActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniTKTongKet);

        mniDSSinhVien.setText("Danh sách sinh viên");
        mniDSSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniDSSinhVienMouseClicked(evt);
            }
        });
        mnuThongKe.add(mniDSSinhVien);

        jMenuBar1.add(mnuThongKe);

        jMenu7.setText("Windows");
        jMenuBar1.add(jMenu7);

        jMenu8.setText("Trợ giúp");
        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMatKhauActionPerformed
        // TODO add your handling code here:
        openDoiMatKhau();
    }//GEN-LAST:event_mniDoiMatKhauActionPerformed

    private void mniQuanLiNguoiDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQuanLiNguoiDungActionPerformed
        // TODO add your handling code here:
        openQuanLiNguoiDung();
    }//GEN-LAST:event_mniQuanLiNguoiDungActionPerformed

    private void mniQuanLiDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQuanLiDiemActionPerformed
        // TODO add your handling code here:
        openQuanLiDiem();
    }//GEN-LAST:event_mniQuanLiDiemActionPerformed

    private void mniTKTongKetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTKTongKetActionPerformed

    }//GEN-LAST:event_mniTKTongKetActionPerformed

    private void mniTKTongKetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniTKTongKetMouseClicked
        ThongKeDAO tkdao = new ThongKeDAO();
        tkdao.selectAll();
        while (true) {
            tkdao.intongketsv();
            break;
        }
        JOptionPane.showMessageDialog(this, "Thống kê tổng kết điểm thành công. Thư mục được chứa ở D://thongketk.xlsx");
    }//GEN-LAST:event_mniTKTongKetMouseClicked

    private void mniTKTongKetMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mniTKTongKetMenuSelected

    }//GEN-LAST:event_mniTKTongKetMenuSelected

    private void mniDSSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniDSSinhVienMouseClicked
        ThongKeDAO dao = new ThongKeDAO();
        dao.selectAllSV();
        while (true) {
            dao.indssv();
            break;
        }
        JOptionPane.showMessageDialog(this, "Thống kê danh sách sinh viên thành công. Thư mục được chứa ở D://thongkedssv.xlsx");
    }//GEN-LAST:event_mniDSSinhVienMouseClicked

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mniExitActionPerformed

    private void mniDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangNhapActionPerformed
        // TODO add your handling code here:
        openDangNhap();
    }//GEN-LAST:event_mniDangNhapActionPerformed

    private void mniMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMonActionPerformed
        // TODO add your handling code here:
        openQuanLiMonHoc();
    }//GEN-LAST:event_mniMonActionPerformed

    private void mniKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKhoaActionPerformed
        // TODO add your handling code here:
        openQuanLiKhoa();
    }//GEN-LAST:event_mniKhoaActionPerformed

    private void mniLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLopActionPerformed
        // TODO add your handling code here:
        openQuanLiLop();
    }//GEN-LAST:event_mniLopActionPerformed

    private void mniQuanLiSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQuanLiSinhVienActionPerformed
        // TODO add your handling code here:
        openQuanLiSinhVien();
    }//GEN-LAST:event_mniQuanLiSinhVienActionPerformed

    private void mniQuanLiGiangVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQuanLiGiangVienActionPerformed
        // TODO add your handling code here:
        openQuanLiGiangVien();
    }//GEN-LAST:event_mniQuanLiGiangVienActionPerformed

    private void btnQLSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSinhVienActionPerformed
        // TODO add your handling code here:
        openQuanLiSinhVien();
    }//GEN-LAST:event_btnQLSinhVienActionPerformed

    private void btnQLGiangVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLGiangVienActionPerformed
        // TODO add your handling code here:
        openQuanLiGiangVien();
    }//GEN-LAST:event_btnQLGiangVienActionPerformed

    private void btnQuanLyDiemSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyDiemSVActionPerformed
        // TODO add your handling code here:
        openQuanLiDiem();
    }//GEN-LAST:event_btnQuanLyDiemSVActionPerformed

    private void btnQLKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLKhoaActionPerformed
        // TODO add your handling code here:
        openQuanLiKhoa();
    }//GEN-LAST:event_btnQLKhoaActionPerformed

    private void btnQLLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLLopActionPerformed
        // TODO add your handling code here:
        openQuanLiLop();
    }//GEN-LAST:event_btnQLLopActionPerformed

    private void btnQLMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLMonHocActionPerformed
        // TODO add your handling code here:
        openQuanLiMonHoc();
    }//GEN-LAST:event_btnQLMonHocActionPerformed

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        // TODO add your handling code here:
        dangXuat();
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void mniTimKiemDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTimKiemDiemActionPerformed
        // TODO add your handling code here:
        openTimKiemDiem();
    }//GEN-LAST:event_mniTimKiemDiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQLGiangVien;
    private javax.swing.JButton btnQLKhoa;
    private javax.swing.JButton btnQLLop;
    private javax.swing.JButton btnQLMonHoc;
    private javax.swing.JButton btnQLSinhVien;
    private javax.swing.JButton btnQuanLyDiemSV;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu mniDSSinhVien;
    private javax.swing.JMenuItem mniDangNhap;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniDoiMatKhau;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniKhoa;
    private javax.swing.JMenuItem mniLop;
    private javax.swing.JMenuItem mniMon;
    private javax.swing.JMenuItem mniQuanLiDiem;
    private javax.swing.JMenuItem mniQuanLiGiangVien;
    private javax.swing.JMenuItem mniQuanLiNguoiDung;
    private javax.swing.JMenuItem mniQuanLiSinhVien;
    private javax.swing.JMenu mniTKTongKet;
    private javax.swing.JMenuItem mniTimKiemDiem;
    private javax.swing.JMenu mnuThongKe;
    private javax.swing.JMenu mnuTimKiem;
    // End of variables declaration//GEN-END:variables
}
